### ISSUE TITLE
CLI Disconnect errors

### ISSUE THREAD

**Issue by wilburforce83** [binary-com/binary-bot#1404]
Hi There, 

I have a consistent error being thrown anywhere between 10 - 120 minutes, on the CLI bot, is there a simple fix to prevent this? at the moment I am unable to use it for trading as the disconnect resets the bot therefore any martingale attached to it?

```11:22:06: INFO: Bought: Win payout if Volatility 100 Index after 3 ticks is strictly lower than entry spot.
11:22:06 Purchased: PUT - Direction is DOWN
11:22:12: SUCCESS: Profit amount: 0.59
11:22:12 =============================================================
11:22:12 ||   Ladder Profit: 0.7199999999999999
11:22:12 ||   Ladders Completed:  0
11:22:12 ||   Peak Profit:  1.3599999999999999
11:22:12 ||   Worst Profit:  0
11:22:12 ||   Session Profit:  0.7199999999999999
11:22:12 ||   Number of Trades:  13
11:22:12 ||   Current Stake:  0.6599771998131329
11:22:12 =============================================================
11:22:16: INFO: Bought: Win payout if Volatility 100 Index after 3 ticks is strictly lower than entry spot.
11:22:16 Purchased: PUT - NO OTHER DATA
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:602:25)
Emitted 'error' event at:
    at WebSocket.finalize (/usr/local/lib/node_modules/binary-bot/lib/index.js:11896:41)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
wilbur-server@basilisk-server:~/binary-bot$ ```

Thanks!

**Comment by aaron-binary** [comment]
Hey @wilburforce83,

The connection will be dropped when there hasn't been any activity on it for a period of time, can you confirm that messages are being sent? You could send a `ping` call every 30 secs or so. https://developers.binary.com/api/#ping

Regards,
Aaron
