### ISSUE TITLE
Pass an env variable into a bot source file

### ISSUE THREAD

**Issue by okovalov** [binary-com/binary-bot#239]
@aminmarashi How can I pass a variable into the bot from the console?

for example I do not want to have apiKey hardcoded into the js file, so I was looking for smth like

API_KEY='XXXX' bot bot-rf-1-R_50.js

and in the bot file I wanted to access it by using

console.log(process.env.API_KEY);

but I got an error

10:34:51 PM Starting bot...
10:34:51 PM Trade started at 6/1/2017, 10:34:51 PM
10:34:51 PM: ReferenceError: process is not defined
    at Interpreter.executeException (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:37436:17)
    at Interpreter.throwException (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:37402:8)
    at Interpreter.getValueFromScope (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:37254:8)
    at Interpreter.stepIdentifier (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:38097:46)
    at Interpreter.step (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:35364:33)
    at Interpreter.run (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:35378:32)
    at Interpreter.loop (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:17884:47)
    at /home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:17879:20
    at Interpreter.run (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:17867:16)
    at Interface.<anonymous> (/home/oleks/.nvm/versions/node/v7.10.0/lib/node_modules/binary-bot/lib/index.js:19254:24)

thx

**Comment by aminmarashi** [comment]
Pretty good idea, though not supported. The bot environment is a sandboxed one, meaning you can't access the things we don't explicitly allow you to.

**Comment by okovalov** [comment]
@aminmarashi thank you.. would be great to have it implemented - some set of allowed env vars to be passed into same script to make it reusable

**Comment by okovalov** [comment]
related to [this issue](https://github.com/binary-com/binary-bot/issues/342)
